server.port=8088
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Lap_Trinh_WEB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=PTrinh@20061999
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

# --- Thư mục lưu file upload (đọc bởi StorageProperties) ---
storage.location=uploads
 
# --- Giới hạn dung lượng upload ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# application.properties
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER